### ISSUE TITLE
fxn naming scheme

### ISSUE THREAD

**Issue by sckott** [njtierney/ukpolice#6]
Something we've been doing in some of our pkgs, is to prefix fxns with something very short, e.g., here could do `ukp` or `up` - so `get_neighbourhoods` could become `ukp_neighbourhoods` 

because R doesn't require users to namespace fxn calls, fxn collisions can happen, so this helps that

and helps users with knowing what pkg a fxn comes from easily

just a thought...

**Comment by njtierney** [comment]
This is a great idea, thanks @sckott ! @masalmon has also suggested this, it is a nice user feature

**Comment by njtierney** [comment]
fixed in the above commit. Thanks again for your suggestion!
