### ISSUE TITLE
curl options

### ISSUE THREAD

**Issue by sckott** [njtierney/ukpolice#7]
I like to allow users (And me as a dev of a pkg) to be able to easily get verbose output on http requests. can do easily with your fxns like

``` r
foo <- function(x, ...) {
    GET(x, ...)
}
foo('bar', config = verbose())
```

and user can pass in any other `httr` curl options, e.g., `timeout` to force a request to timeout, etc. 

this often comes in handy when a user is having trouble, you can ask them to add a `config = httr::verbose()` to their call, and send you the output

**Comment by njtierney** [comment]
Thanks for this, @sckott , I think I've done this now in the commit above, is that what you were referring to?

**Comment by sckott** [comment]
yeah, except for `ukp_neighbourhood` needs a `...` as well

**Comment by njtierney** [comment]
OK great, thanks! I think that's it, right?

**Comment by sckott** [comment]
usually also direct people to docs for `httr::GET` or whatever verb you're using

**Comment by njtierney** [comment]
In the documentation for `...` you mean?

**Comment by sckott** [comment]
yeah

**Comment by njtierney** [comment]
OK, I think this is all good now, I'm going to close the issue for the moment. Thanks again, @sckott !
